<?php

/**
 * @file
 * This module provides tools to integrate elasticsearch with Drupal.
 */

require drupal_get_path('module', 'elasticsearch_helper') . '/vendor/autoload.php';


/**
 * Implements hook_entity_insert().
 */
function elasticsearch_helper_menu() {
  $items['admin/config/search/elasticsearch_helper'] = [
    'title' => 'Elasticsearch Helper',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elasticsearch_helper_settings_form'),
    'access arguments' => array('configure elasticsearch helper'),
    'file' => 'elasticsearch_helper.admin.inc',
  ];

  return $items;
}

function elasticsearch_helper_get_client() {
  static $elasticsearch_helper__client;

  if (! isset($elasticsearch_helper__client)) {
    require drupal_get_path('module', 'elasticsearch_helper') . "/src/ElasticsearchClientBuilder.php";
    $builder = new ElasticsearchClientBuilder();
    $elasticsearch_helper__client = $builder->build();
  }

  return $elasticsearch_helper__client;
}