elasticsearch_helper.settings:
  type: config_object
  label: 'Elasticsearch helper config.'
  mapping:
    hosts:
      type: sequence
      sequence:
        scheme:
          type: string
          label: Scheme
        host:
          type: string
          label: Host
        port:
          type: integer
          label: Port
        authentication:
          type: mapping
          label: Authentication
          mapping:
            enabled:
              type: integer
              label: Enabled
            user:
              type: string
              label: User
            password:
              type: string
              label: Password
    defer_indexing:
      type: boolean
      label: 'Defer indexing'
