elasticsearch_helper.settings:
  type: config_object
  label: 'Elasticsearch helper config.'
  mapping:
    scheme:
      type: string
      label: Scheme
    hosts:
      type: sequence
      sequence:
        type: mapping
        label: Host
        mapping:
          host:
            type: string
            label: Host
          port:
            type: string
            label: Port
    authentication:
      type: mapping
      label: Authentication
      mapping:
        basic_auth:
          type: mapping
          label: 'Basic auth authentication'
          mapping:
            user:
              type: string
              label: User
            password:
              type: string
              label: Password
        api_key:
          type: mapping
          label: 'API key authentication'
          mapping:
            id:
              type: string
              label: 'API key ID'
            api_key:
              type: string
              label: 'API key'
    ssl:
      type: mapping
      label: 'SSL connection settings'
      mapping:
        certificate:
          type: string
          label: 'SSL certificate path'
        skip_verification:
          type: boolean
          label: 'Skip SSL certificate verification'
    defer_indexing:
      type: boolean
      label: 'Defer indexing'
